# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache D:/1/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-13296-MateBookXPro/incrSyn
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.cache/wt [current_project]
set_property parent.project_path D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Five_stage_RISC_V/test.dat
read_verilog -library xil_defaultlib -sv {
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/ALU.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/new/ALU_Input_Mux.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/new/Branch_Misprediction_Unit.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Branch_Predictor.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/new/Branch_Target_Unit.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Controller.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Ex_Mem_reg.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Forwarding_Unit.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Hazard_Detection_Unit.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/ID_Ex_reg.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/IF_ID_reg.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Immediate_Generator.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/new/JAL_Detection_Unit.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Mem_Wr_reg.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/PC.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/new/PC_Mux.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Register_File.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/imports/Project/Unified_Memory.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/new/Wr_Mux.sv
  D:/1/desktop/Five_stage_RISC_V/RISC_V/RISC_V.srcs/sources_1/new/RISC_V_CPU_Top.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top RISC_V_CPU_Top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RISC_V_CPU_Top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RISC_V_CPU_Top_utilization_synth.rpt -pb RISC_V_CPU_Top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
